security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_userprovider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/((profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login           # GET - muestra formulario
                check_path: app_login_check     # POST - procesa autenticación
                enable_csrf: true
                # Opcional: puedes agregar esto para más claridad
                username_parameter: _username
                password_parameter: _password

            logout:
                path: app_logup

    access_control:
        # Página principal y API accesibles sin autenticación

        
{ path: ^/api, roles: PUBLIC_ACCESS }
{ path: ^/login$, roles: PUBLIC_ACCESS }
{ path: ^/login_check$, roles: PUBLIC_ACCESS }
  # El resto requiere autenticación
{ path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10