[phases.setup]
nixPkgs = ["php", "nginx", "libmysqlclient", "phpPackages.composer", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
    "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm i"
]

[phases.build]
cmds = [
    "composer dump-env prod",
    "php bin/console cache:clear --env=prod --no-debug",
    "php bin/console asset-map:compile"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
